version: "3.8"

services:
  aws-glue:
    command: /home/glue_user/jupyter/jupyter_start.sh
    image: amazon/aws-glue-libs:glue_libs_2.0.0_image_01
    volumes:
      - ~/.aws:/home/glue_user/.aws
      - ./volumes/jupyter:/home/glue_user/workspace/jupyter_workspace/
      - ./volumes/maven_jars:/home/glue_user/workspace/lib/
      - ./volumes/python-packages/:/extra_python_packages/
      - ./volumes/maven_jars:/extra_jars/
    environment:
      AWS_PROFILE: ben-ai-sandbox
      DISABLE_SSL: "true"
      PYTHONPATH: '$PYTHONPATH:/extra_python_packages/'
      AWS_REGION: us-east-2
    ports:
      - 4040:4040
      - 18080:18080
      - 8998:8998
      - 8888:8888
