install:
    pip install -e .

install-glue-jupyter-dependencies:
    #!/bin/bash
    cd ./resources/glue

    # install external python packages into glue ./volume/python-packages;
    # these need to be installed in a Python 3.7 linux environment (not a Mac)
    # because that is the environment Glue 2.0 uses
    docker run --rm \
        --entrypoint python \
        -v $PWD/python-packages:/packages \
        python:3.7-slim-buster \
            -m pip install simple-salesforce -t /packages

    # fetch the maven jars needed by glue; TODO: we arent
    # able to get these into spark-submit or jupyter-lab...
    # so this step isnt useful for local development until we figure that out
    python -m pip install -r fetch-maven.requirements.txt
    python fetch_maven_jars.py


start-glue-jupyter:
    cd ./resources/glue/ && docker-compose up